[build]
builder = "NIXPACKS"

[deploy]
startCommand = "npm start"
healthcheckPath = "/api/me"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production]
JWT_SECRET = "your-super-secret-jwt-key-here-12345"
ADMIN_PASSWORD = "admin123"
NODE_ENV = "production"
