services:
  - type: web
    name: report-intel
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_PASSWORD
        value: admin123
      - key: PORT
        value: 10000
    healthCheckPath: /
    autoDeploy: true
