-- Report Intelligence Database Schema
-- Run this script to initialize your Supabase database

-- Create reports table
CREATE TABLE IF NOT EXISTS reports (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  title TEXT NOT NULL,
  upload_date TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  size_kb NUMERIC NOT NULL,
  extracted_date TEXT,
  status TEXT DEFAULT 'uploaded' NOT NULL CHECK (status IN ('uploaded', 'analyzed', 'published')),
  content_url TEXT,
  files JSONB DEFAULT '[]'::jsonb NOT NULL,
  ai_json JSONB,
  ai_markdown TEXT,
  score NUMERIC,
  updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  is_published BOOLEAN DEFAULT FALSE NOT NULL
);

-- Create indexes for better performance
CREATE INDEX IF NOT EXISTS reports_updated_at_idx ON reports (updated_at DESC);
CREATE INDEX IF NOT EXISTS reports_is_published_idx ON reports (is_published) WHERE is_published = TRUE;
CREATE INDEX IF NOT EXISTS reports_status_idx ON reports (status);
CREATE INDEX IF NOT EXISTS reports_score_idx ON reports (score) WHERE score IS NOT NULL;

-- Create storage bucket for report files
INSERT INTO storage.buckets (id, name, public) 
VALUES ('reports_files', 'reports_files', true)
ON CONFLICT (id) DO NOTHING;

-- Set up Row Level Security (RLS) policies
-- Note: For this application, we'll disable RLS and use service role for API access
-- In production, you might want to enable RLS and create appropriate policies

ALTER TABLE reports DISABLE ROW LEVEL SECURITY;

-- Storage policies for reports_files bucket
CREATE POLICY IF NOT EXISTS "Public read access for reports_files" 
ON storage.objects FOR SELECT 
USING (bucket_id = 'reports_files');

CREATE POLICY IF NOT EXISTS "Authenticated users can upload to reports_files" 
ON storage.objects FOR INSERT 
WITH CHECK (bucket_id = 'reports_files');

CREATE POLICY IF NOT EXISTS "Authenticated users can update reports_files" 
ON storage.objects FOR UPDATE 
USING (bucket_id = 'reports_files');

CREATE POLICY IF NOT EXISTS "Authenticated users can delete from reports_files" 
ON storage.objects FOR DELETE 
USING (bucket_id = 'reports_files');

-- Create updated_at trigger
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_reports_updated_at 
    BEFORE UPDATE ON reports 
    FOR EACH ROW 
    EXECUTE FUNCTION update_updated_at_column();

-- Sample data (remove this in production)
-- This is for testing purposes only
INSERT INTO reports (
  title, 
  size_kb, 
  status, 
  files,
  ai_json,
  ai_markdown,
  score,
  is_published
) VALUES (
  'Sample Market Analysis Report',
  2048,
  'published',
  '[{"type": "pdf", "url": "https://example.com/sample.pdf", "file_name": "sample.pdf", "size_kb": 2048}]'::jsonb,
  '{
    "kpis": [
      {"name": "Revenue Growth", "value": "+15.3%", "description": "vs. Previous Quarter", "trend": "up", "percentage": 76.5},
      {"name": "Market Share", "value": "34.2%", "description": "Total Addressable Market", "trend": "up", "percentage": 34.2}
    ],
    "trend_summary": "Strong growth across all metrics with positive market indicators",
    "insights": ["Market expansion opportunities identified", "Competitive positioning improved"],
    "score": 8.7,
    "charts": [
      {
        "type": "line",
        "title": "Revenue Trends",
        "data": [
          {"month": "Q1", "revenue": 2300000},
          {"month": "Q2", "revenue": 2800000},
          {"month": "Q3", "revenue": 3200000},
          {"month": "Q4", "revenue": 3800000}
        ],
        "xAxisKey": "month",
        "yAxisKey": "revenue"
      }
    ],
    "next_month_plan": {
      "weekly_plan": [
        [{"title": "Market Research", "description": "Complete competitive analysis"}],
        [{"title": "Product Development", "description": "Begin feature development"}],
        [{"title": "Implementation", "description": "Deploy new features"}],
        [{"title": "Analysis", "description": "Measure results"}]
      ],
      "milestones": [
        {"title": "Complete Market Analysis", "date": "2024-12-22", "completed": false}
      ],
      "risks_mitigations": [
        {"title": "Market Volatility", "mitigation": "Monitor daily indicators", "severity": "medium"}
      ]
    }
  }'::jsonb,
  'This is a comprehensive market analysis showing strong performance across key metrics with significant growth opportunities identified.',
  8.7,
  true
) ON CONFLICT DO NOTHING;
